# Quick Start
# $ xhost +
# $ docker compose up

version: "2.3"

services:

  # ROS Galactic
  vulcanexus:
    image: donowak/vulcanexus
    network_mode: host
    ipc: host
    volumes: 
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    environment:
      - DISPLAY
    command: fastdds_monitor