# Quick Start
# $ xhost local:root
# $ docker compose -f compose.pc.yaml up

version: "2.3"

services:

  # ROS Galactic
  vulcanexus:
    build: .
    network_mode: host
    ipc: host
    volumes: 
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    environment:
      # - ROS_DOMAIN_ID=228
      - DISPLAY